# -*- coding: utf-8 -*-
"""matplotlib notes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1in5zi73mjG1mfHXAK1aOdual8TbI1e0E
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

plt.figure(figsize=(5,3), dpi=100)

plt.plot(x, y, label = '2x', color = 'brown',linestyle='--',linewidth=2,
         marker='.', markersize=10, markeredgecolor='yellow')

x2 = np.arange(0, 4.5, 0.5)
plt.plot(x2, x2**2)

plt.title('Our First Graph!')
plt.xlabel('X axis')
plt.ylabel('Y axis')

plt.legend()
plt.show()

labels =['A','B','C']
values = [1,4,2]

plt.bar(labels, values)
plt.figure(figsize = (6, 4))
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

gas = pd.read_csv('gas_prices.csv')

gas

gas = pd.read_csv('gas_prices.csv')

plt.plot(gas.Year, gas.USA)
plt.plot(gas.Year, gas.Canada)

plt.show()

gas = pd.read_csv('gas_prices.csv')

plt.figure(figsize =(7, 4))

plt.title('Gas Prices Over Time (in USD)')

plt.plot(gas.Year, gas.USA, label = 'USA')
plt.plot(gas['Year'], gas.Canada, label = 'Canada')
plt.plot(gas['Year'], gas['South Korea'], label = 'South Korea')
plt.plot(gas['Year'], gas['Australia'], label = 'Australia')

# countries_to_look_at = ['Australia','USA','Canada','South Korea']
# for country in countries_to_look_at:
#   if country != 'Year':
#     plt.plot(gas.Year, gas[country], marker = '.')

print(gas.Year[::3])
print(gas.Year[::3].tolist()+[2011])

plt.xlabel('Year')
plt.ylabel('US Dollars')

plt.legend()
plt.savefig('Gas_price_figure.png', dpi=300)
plt.show()